export const FETCH_REQUEST_START = 'FETCH_REQUEST_START'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE'

export const SET_POST_COMMENT = 'SET_POST_COMMENT'