export const FETCH_REQUEST_START = 'COMMENTS/FETCH_REQUEST_START'
export const FETCH_REQUEST_SUCCESS = 'COMMENTS/FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_FAILURE = 'COMMENTS/FETCH_REQUEST_FAILURE'